### ISSUE TITLE
AssertionError when running tt month

### ISSUE THREAD

**Issue by marty331** [globau/timetracker#1]
When I run tt month I get an AssertionError.  In looking at the code I see that it's comparing the timezone in the Edit datetime to the current timezone.  Whenever you have been through a change in daylight savings time this error will be thrown.  My question is, is this assert statement really needed?  If so, what is the purpose of comparing the timezones?

`Traceback (most recent call last):
  File "/Users/marty331/Dev/timetracker/src/harness.py", line 76, in __init__
    main()
  File "/Users/marty331/Dev/timetracker/src/main.py", line 30, in main
    cli()
  File "/Users/marty331/Dev/timetracker/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marty331/Dev/timetracker/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/marty331/Dev/timetracker/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marty331/Dev/timetracker/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marty331/Dev/timetracker/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/marty331/Dev/timetracker/src/commands/monthly.py", line 52, in month
    for edit in database.edits(days[ymd]["dt"]):
  File "/Users/marty331/Dev/timetracker/src/database.py", line 248, in edits
    assert dt.datetime.tzname() == cfg.time_zone_name
AssertionError`

**Comment by globau** [comment]
sorry about the slow response - github didn't notify me of this issue.

i think you're right that the assert isn't necessary; will check before removing.
